In [9]:
import torch

torch.manual_seed(0)

n_features = 3
n_embed = 2
n_batch = 1

batch = torch.randn(n_batch, n_features)
# round to 0.1
batch = torch.round(batch * 10) / 10

w = torch.randn(n_features, n_embed)
w = torch.round(w * 10) / 10

print(batch)
print()

print(w)
print()

out = batch.view(n_batch, n_features, 1) * w

print(out)
print()



tensor([[ 1.5000, -0.3000, -2.2000]])

tensor([[ 0.6000, -1.1000],
        [-1.4000,  0.4000],
        [ 0.8000, -0.7000]])

tensor([[[ 0.9000, -1.6500],
         [ 0.4200, -0.1200],
         [-1.7600,  1.5400]]])



In [5]:
import torch
import torch.nn as nn

n_categorical = [2, 3, 2]
n_embed = 4

weight = torch.arange(sum(n_categorical) * n_embed).view(sum(n_categorical), n_embed)
bias = torch.arange(len(n_categorical) * n_embed).view(len(n_categorical), n_embed)

print(weight)
print(bias)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [6]:
offsets = torch.tensor([0] + n_categorical[:-1]).cumsum(dim=0)
print(offsets)

sample = torch.tensor([[1, 2, 0], [0, 1, 1]])
print(sample)

embedded = weight[sample + offsets]
print(embedded)

embedded + bias

tensor([0, 2, 5])
tensor([[1, 2, 0],
        [0, 1, 1]])
tensor([[[ 4,  5,  6,  7],
         [16, 17, 18, 19],
         [20, 21, 22, 23]],

        [[ 0,  1,  2,  3],
         [12, 13, 14, 15],
         [24, 25, 26, 27]]])


tensor([[[ 4,  6,  8, 10],
         [20, 22, 24, 26],
         [28, 30, 32, 34]],

        [[ 0,  2,  4,  6],
         [16, 18, 20, 22],
         [32, 34, 36, 38]]])

In [31]:
# For continuous
n_features = 100
n_embed = 100
sample = torch.randn(n_features, dtype=torch.float32).view(1, -1)


weight = torch.randn(n_features * n_embed, dtype=torch.float32).view(n_features, n_embed)
bias = torch.randn(n_features * n_embed, dtype=torch.float32).view(n_features, n_embed)

out = sample.view(1, -1, 1) * weight + bias
# print(out)
print()

print(out.mean(dim=1))
print(out.std(dim=1))
print()

print(out.mean(dim=2))
print(out.std(dim=2))


tensor([[-3.2076e-01, -9.5776e-02, -1.1979e-01, -7.7094e-02, -4.2798e-02,
          5.2860e-02,  7.0318e-02, -6.8949e-02, -3.2002e-02,  1.3419e-01,
          2.6229e-05,  2.3014e-01,  1.9460e-01, -1.6095e-01, -1.4694e-01,
         -1.7219e-01, -3.8037e-02, -5.0943e-02, -1.7330e-01, -1.7146e-02,
         -5.1742e-02, -1.0452e-01, -3.5777e-02, -1.0830e-01, -3.0634e-02,
          5.7191e-02, -9.1435e-02,  9.5385e-03,  1.1736e-01,  1.1008e-01,
         -3.4450e-01, -1.1643e-01, -2.7607e-01, -5.0682e-02, -1.3717e-01,
         -2.4952e-01,  1.2766e-01,  2.0956e-01,  1.3261e-01,  3.0344e-03,
         -3.5138e-01, -4.2625e-01,  1.3518e-01,  2.5209e-02,  4.0887e-02,
         -5.0278e-03, -1.7400e-01,  1.6538e-01,  2.5382e-01, -2.9306e-02,
          3.8212e-02,  7.6003e-03,  2.8308e-01,  6.5976e-02, -8.4690e-02,
         -7.2777e-02,  9.5577e-03,  2.1656e-01, -1.2756e-01, -2.7651e-01,
          2.5726e-01,  2.4260e-01, -6.8130e-02,  1.9406e-02,  5.4119e-02,
         -4.1692e-02, -1.4601e-01,  1

In [52]:
import numpy as np

raw = np.array([200, 4], dtype=float)
weighted = np.array([100, 8], dtype=float)

freq_raw = raw / raw.sum()
freq_weighted = weighted / weighted.sum()
averages = weighted / raw

# print(freq_raw)
# print(freq_weighted)

print(raw)
print(weighted)
print(1 / freq_raw)
print(1 / freq_raw * weighted)
print(freq_raw * freq_weighted)
print(1 / (freq_raw * freq_weighted))
print(averages.sum() / averages)


[200.   4.]
[100.   8.]
[ 1.02 51.  ]
[102. 408.]
[0.90777052 0.00145243]
[  1.1016 688.5   ]
[5.   1.25]
